version: 0.1.0

name: Jekyll AWS website
description: Deploy a Jekyll website to AWS

branding:
  icon: 'layout'
  color: 'green'

inputs:
  - name: AWS_ACCESS_KEY_ID
    description: aws access key id
    is-secret: true

  - name: AWS_SECRET_ACCESS_KEY
    description: aws secret access key
    is-secret: true

  - name: DOMAIN_NAME
    description: domain name of the website

  - name: HOST_NAME
    default: www
    description: host name of website

  - name: HOSTED_ZONE_ID
    description: aws route53 hosted zone id

configs:
  repo-metadata:
    parameters:
      description: 'Jekyll website on AWS'
      secrets:
      - name: AWS_ACCESS_KEY_ID
        value: ${{inputs.AWS_ACCESS_KEY_ID}}
      - name: AWS_SECRET_ACCESS_KEY
        value: ${{inputs.AWS_SECRET_ACCESS_KEY}}
      - name: DOMAIN_NAME
        value: ${{inputs.DOMAIN_NAME}}
      - name: HOST_NAME
        value: ${{inputs.HOST_NAME}}
      - name: HOSTED_ZONE_ID
        value: ${{inputs.HOSTED_ZONE_ID}}
  branches:
    - name: main
      parameters:
        enforce-admins: true
        required-pull-request-reviews:
          dismiss-stale-reviews: true
          required-approving-review-count: 1

init:
  uses: stack-init.yaml