version: 0.1.0

name: Jekyll AWS website
description: Deploy a Jekyll website to AWS

branding:
  icon: 'layout'
  color: 'green'

inputs:
  - name: AWS_ACCESS_KEY_ID
    description: aws access key id
    is-secret: true
    required: true

  - name: AWS_SECRET_ACCESS_KEY
    description: aws secret access key
    is-secret: true
    required: true

  - name: DOMAIN_NAME
    description: domain name of the website
    required: true

  - name: HOST_NAME
    default: www
    description: host name of website
    required: true

  - name: HOSTED_ZONE_ID
    description: aws route53 hosted zone id
    required: true

configs:
  repo-metadata:
    parameters:
      description: 'Jekyll static website on AWS'
      topics:
        - jekyll
        - aws

  branches:
    - name: main
      parameters:
        allow-force-pushes: false
        allow-deletions: false
        enforce-admins: false
        required-pull-request-reviews:
          dismiss-stale-reviews: true
          require-code-owner-reviews: true
          required-approving-review-count: 1
  environments:
    - name: production
      parameters:
        allowed-branch-rules:
          - main
        secrets:
          - name: AWS_ACCESS_KEY_ID
            value: ${{ inputs.AWS_ACCESS_KEY_ID }}
          - name: AWS_SECRET_ACCESS_KEY
            value: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
init:
  uses: stack-init.yaml