AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  DomainName:
    Description: Name of the domain
    Type: String
    ConstraintDescription: must be the name of an existing Hosted Zone in Route53.
  HostName:
    Description: Hostname part of the URL for the website.
    Type: String
  HostedZoneId:
    Description: Hosted Zone ID needed for SSL certificate validation.
    Type: String

Resources:
  CloudFrontS3IndexHtml:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-cloudFrontS3IndexHtml
      Description: CloudFront S3 index.html edge lambda
      Handler: index.handler
      CodeUri: src/cloudFrontS3IndexHtml
      Runtime: nodejs14.x
      Timeout: 5
      AutoPublishAlias: riznob
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
            - edgelambda.amazonaws.com
          Action: sts:AssumeRole
  DeploymentLayer:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:375983427419:applications/deploy-to-s3
        SemanticVersion: 2.4.2
  SiteSource:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
        - !GetAtt DeploymentLayer.Outputs.Arn
      CodeUri: web/_site
      AutoPublishAlias: live
      Runtime: python3.7
      Handler: deployer.resource_handler
      Timeout: 600
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref S3Bucket
  DeploymentResource:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt SiteSource.Arn
      Version: !Ref "SiteSource.Version"
      TargetBucket: !Ref S3Bucket
      Acl: 'private'
      CacheControlMaxAge: 600
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:  
        Statement:  
        - Action: 's3:GetObject'
          Effect: "Allow"  
          Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"
          Principal: 
            AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontDistributionOriginAccessIdentity}" 
  SSLCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: !Sub '${HostName}.${DomainName}'
      DomainValidationOptions:
      - DomainName: !Sub '${HostName}.${DomainName}'
        HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS
  CloudFrontDistributionOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties: 
      CloudFrontOriginAccessIdentityConfig: 
        Comment: !Sub ${AWS::StackName}-access-identity
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !GetAtt S3Bucket.DomainName
          Id: !Ref S3Bucket
          S3OriginConfig:
            OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontDistributionOriginAccessIdentity}
        Enabled: 'true'
        HttpVersion: http2
        Aliases:
        - !Sub ${HostName}.${DomainName}
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          TargetOriginId: !Ref S3Bucket
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
          LambdaFunctionAssociations:
          - EventType: origin-request
            LambdaFunctionARN: !Ref EdgeLambdaArn
        ViewerCertificate:
          AcmCertificateArn: !Ref SSLCertificate
          SslSupportMethod: sni-only
  DNSRecord:
    Type: 'AWS::Route53::RecordSetGroup'
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
        - Name: !Sub '${HostName}.${DomainName}.'
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt CloudFrontDistribution.DomainName
Outputs:
  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution
  S3Bucket:
    Description: S3 Bucket
    Value: !Ref S3Bucket