name: "build"

on: [push]

defaults:
  run:
    shell: bash
    working-directory: web

jobs:  run:    shell: bash    working-directory: scripts
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - run: bundle install
    - run: bundle exec jekyll build
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: jekyll-site
        path: _site/**/*
        retention-days: 1