name: Build and deploy to aws s3

on:
  push:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: web

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - run: bundle install
    - run: bundle exec jekyll build
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: jekyll-site
        path: _site/**/*
        retention-days: 1
  deploy-to-production:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: jekyll-site
        path: _site
    - name: S3 Sync
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: _site
    - name: Invalidate Cloudfront
      uses: chetan/invalidate-cloudfront-action@v1.2
      env:
        DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
        PATHS: '/*'
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}